import type { Metadata } from "next";
import { Footer, Header } from "@/components";
import { ReduxProvider } from "./redux/provider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Lucas Eitel assignment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <ReduxProvider>
          <Header />
          {children}
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  );
}
